<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Багийн нэр / гишүүдийн нэрс">

<title>Naive Bayes ашиглан social media донтолтын түвшин тогтоох нь</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Агуулга</h2>
   
  <ul>
  <li><a href="#оршил" id="toc-оршил" class="nav-link active" data-scroll-target="#оршил"><span class="header-section-number">1</span> Оршил</a></li>
  <li><a href="#судалгааны-зорилго-ба-зорилтууд" id="toc-судалгааны-зорилго-ба-зорилтууд" class="nav-link" data-scroll-target="#судалгааны-зорилго-ба-зорилтууд"><span class="header-section-number">2</span> Судалгааны зорилго ба зорилтууд</a>
  <ul class="collapse">
  <li><a href="#ерөнхий-зорилго" id="toc-ерөнхий-зорилго" class="nav-link" data-scroll-target="#ерөнхий-зорилго"><span class="header-section-number">2.1</span> Ерөнхий зорилго</a></li>
  <li><a href="#тусгай-зорилтууд" id="toc-тусгай-зорилтууд" class="nav-link" data-scroll-target="#тусгай-зорилтууд"><span class="header-section-number">2.2</span> Тусгай зорилтууд</a></li>
  </ul></li>
  <li><a href="#судалгааны-өгөгдөл" id="toc-судалгааны-өгөгдөл" class="nav-link" data-scroll-target="#судалгааны-өгөгдөл"><span class="header-section-number">3</span> Судалгааны өгөгдөл</a>
  <ul class="collapse">
  <li><a href="#өгөгдлийн-эх-сурвалж-ба-ерөнхий-тайлбар" id="toc-өгөгдлийн-эх-сурвалж-ба-ерөнхий-тайлбар" class="nav-link" data-scroll-target="#өгөгдлийн-эх-сурвалж-ба-ерөнхий-тайлбар"><span class="header-section-number">3.1</span> Өгөгдлийн эх сурвалж ба ерөнхий тайлбар</a></li>
  <li><a href="#өгөгдөл-бэлтгэл" id="toc-өгөгдөл-бэлтгэл" class="nav-link" data-scroll-target="#өгөгдөл-бэлтгэл"><span class="header-section-number">3.2</span> Өгөгдөл бэлтгэл</a></li>
  <li><a href="#train-болон-dev-өгөгдлийн-бүтэц" id="toc-train-болон-dev-өгөгдлийн-бүтэц" class="nav-link" data-scroll-target="#train-болон-dev-өгөгдлийн-бүтэц"><span class="header-section-number">3.3</span> Train болон dev өгөгдлийн бүтэц</a></li>
  <li><a href="#тоон-хувьсагчдын-статистик-шинжилгээ" id="toc-тоон-хувьсагчдын-статистик-шинжилгээ" class="nav-link" data-scroll-target="#тоон-хувьсагчдын-статистик-шинжилгээ"><span class="header-section-number">3.4</span> Тоон хувьсагчдын статистик шинжилгээ</a></li>
  </ul></li>
  <li><a href="#онолын-үндэс" id="toc-онолын-үндэс" class="nav-link" data-scroll-target="#онолын-үндэс"><span class="header-section-number">4</span> Онолын үндэс</a>
  <ul class="collapse">
  <li><a href="#байесын-теорем" id="toc-байесын-теорем" class="nav-link" data-scroll-target="#байесын-теорем"><span class="header-section-number">4.1</span> Байесын теорем</a></li>
  <li><a href="#naive-буюу-хараат-бусын-таамаглал" id="toc-naive-буюу-хараат-бусын-таамаглал" class="nav-link" data-scroll-target="#naive-буюу-хараат-бусын-таамаглал"><span class="header-section-number">4.2</span> Naive буюу хараат бусын таамаглал</a></li>
  <li><a href="#тоон-хувьсагчдад-gaussian-naive-bayes-ашиглах" id="toc-тоон-хувьсагчдад-gaussian-naive-bayes-ашиглах" class="nav-link" data-scroll-target="#тоон-хувьсагчдад-gaussian-naive-bayes-ашиглах"><span class="header-section-number">4.3</span> Тоон хувьсагчдад Gaussian Naive Bayes ашиглах</a></li>
  <li><a href="#категори-хувьсагчдад-laplace-smoothing-ашиглах" id="toc-категори-хувьсагчдад-laplace-smoothing-ашиглах" class="nav-link" data-scroll-target="#категори-хувьсагчдад-laplace-smoothing-ашиглах"><span class="header-section-number">4.4</span> Категори хувьсагчдад Laplace smoothing ашиглах</a></li>
  <li><a href="#log-probability-ашиглах-шалтгаан" id="toc-log-probability-ашиглах-шалтгаан" class="nav-link" data-scroll-target="#log-probability-ашиглах-шалтгаан"><span class="header-section-number">4.5</span> Log probability ашиглах шалтгаан</a></li>
  </ul></li>
  <li><a href="#загварын-хэрэгжүүлэлт" id="toc-загварын-хэрэгжүүлэлт" class="nav-link" data-scroll-target="#загварын-хэрэгжүүлэлт"><span class="header-section-number">5</span> Загварын хэрэгжүүлэлт</a>
  <ul class="collapse">
  <li><a href="#project-ийн-кодын-бүтэц" id="toc-project-ийн-кодын-бүтэц" class="nav-link" data-scroll-target="#project-ийн-кодын-бүтэц"><span class="header-section-number">5.1</span> Project-ийн кодын бүтэц</a></li>
  <li><a href="#өгөгдөл-унших-ба-боловсруулах-код" id="toc-өгөгдөл-унших-ба-боловсруулах-код" class="nav-link" data-scroll-target="#өгөгдөл-унших-ба-боловсруулах-код"><span class="header-section-number">5.2</span> Өгөгдөл унших ба боловсруулах код</a></li>
  <li><a href="#naive-bayes-загвар-сургах" id="toc-naive-bayes-загвар-сургах" class="nav-link" data-scroll-target="#naive-bayes-загвар-сургах"><span class="header-section-number">5.3</span> Naive Bayes загвар сургах</a></li>
  <li><a href="#таамаглал-гаргах" id="toc-таамаглал-гаргах" class="nav-link" data-scroll-target="#таамаглал-гаргах"><span class="header-section-number">5.4</span> Таамаглал гаргах</a></li>
  </ul></li>
  <li><a href="#загварын-үнэлгээ" id="toc-загварын-үнэлгээ" class="nav-link" data-scroll-target="#загварын-үнэлгээ"><span class="header-section-number">6</span> Загварын үнэлгээ</a>
  <ul class="collapse">
  <li><a href="#үнэлгээний-хэмжүүрүүд" id="toc-үнэлгээний-хэмжүүрүүд" class="nav-link" data-scroll-target="#үнэлгээний-хэмжүүрүүд"><span class="header-section-number">6.1</span> Үнэлгээний хэмжүүрүүд</a></li>
  <li><a href="#тооцоолсон-үр-дүн" id="toc-тооцоолсон-үр-дүн" class="nav-link" data-scroll-target="#тооцоолсон-үр-дүн"><span class="header-section-number">6.2</span> Тооцоолсон үр дүн</a></li>
  <li><a href="#confusion-matrix" id="toc-confusion-matrix" class="nav-link" data-scroll-target="#confusion-matrix"><span class="header-section-number">6.3</span> Confusion matrix</a></li>
  <li><a href="#ангилал-тус-бүрийн-тайлбар" id="toc-ангилал-тус-бүрийн-тайлбар" class="nav-link" data-scroll-target="#ангилал-тус-бүрийн-тайлбар"><span class="header-section-number">6.4</span> Ангилал тус бүрийн тайлбар</a></li>
  </ul></li>
  <li><a href="#үр-дүнгийн-хэлэлцүүлэг" id="toc-үр-дүнгийн-хэлэлцүүлэг" class="nav-link" data-scroll-target="#үр-дүнгийн-хэлэлцүүлэг"><span class="header-section-number">7</span> Үр дүнгийн хэлэлцүүлэг</a></li>
  <li><a href="#ёс-зүйн-анхаарах-зүйл" id="toc-ёс-зүйн-анхаарах-зүйл" class="nav-link" data-scroll-target="#ёс-зүйн-анхаарах-зүйл"><span class="header-section-number">8</span> Ёс зүйн анхаарах зүйл</a></li>
  <li><a href="#дүгнэлт" id="toc-дүгнэлт" class="nav-link" data-scroll-target="#дүгнэлт"><span class="header-section-number">9</span> Дүгнэлт</a></li>
  <li><a href="#багийн-гишүүдийн-оролцоо" id="toc-багийн-гишүүдийн-оролцоо" class="nav-link" data-scroll-target="#багийн-гишүүдийн-оролцоо"><span class="header-section-number">10</span> Багийн гишүүдийн оролцоо</a></li>
  <li><a href="#ашигласан-материал" id="toc-ашигласан-материал" class="nav-link" data-scroll-target="#ашигласан-материал"><span class="header-section-number">11</span> Ашигласан материал</a></li>
  <li><a href="#хавсралт-ажиллуулах-команд" id="toc-хавсралт-ажиллуулах-команд" class="nav-link" data-scroll-target="#хавсралт-ажиллуулах-команд"><span class="header-section-number">12</span> Хавсралт: Ажиллуулах команд</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="../report.pdf"><i class="bi bi-file-pdf"></i>Typst</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Naive Bayes ашиглан social media донтолтын түвшин тогтоох нь</h1>
<p class="subtitle lead">Gen Z хэрэглэгчдийн social media хэрэглээний өгөгдөл дээр хийсэн машин сургалтын төсөл</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Багийн нэр / гишүүдийн нэрс </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026 оны 5-р сарын 14</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    Энэхүү ажлаар Gen Z хэрэглэгчдийн social media хэрэглээний өгөгдөлд тулгуурлан хэрэглэгчийн донтолтын түвшинг Low, Medium, High гэсэн гурван ангилалд Naive Bayes алгоритмаар ангилах загвар боловсруулав. Өгөгдлийг цэвэрлэж, сургалтын болон хөгжүүлэлтийн хэсэгт хуваан, тоон хувьсагчдад Gaussian Naive Bayes, категори хувьсагчдад Laplace smoothing бүхий categorical Naive Bayes ашигласан. Загварыг 200,000 мөр хөгжүүлэлтийн өгөгдөл дээр шалгахад accuracy 93.05 хувь, macro F1-score 92.29 хувь гарсан.
  </div>
</div>


</header>


<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>ROOT <span class="op">=</span> Path.cwd()</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">str</span>(ROOT) <span class="kw">not</span> <span class="kw">in</span> sys.path:</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    sys.path.insert(<span class="dv">0</span>, <span class="bu">str</span>(ROOT))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.config <span class="im">import</span> CATEGORICAL_COLUMNS</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.config <span class="im">import</span> FEATURE_COLUMNS</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.config <span class="im">import</span> NUMERIC_COLUMNS</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.config <span class="im">import</span> TARGET_COLUMN</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.dataset <span class="im">import</span> read_dataset</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.metrics <span class="im">import</span> classification_report</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.naive_bayes <span class="im">import</span> NaiveBayes</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>train_data, dev_data <span class="op">=</span> read_dataset()</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>metadata <span class="op">=</span> json.loads(</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    Path(<span class="st">"data/processed/metadata.json"</span>).read_text(encoding<span class="op">=</span><span class="st">"utf-8"</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>saved_metrics <span class="op">=</span> json.loads(</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    Path(<span class="st">"outputs/metrics.json"</span>).read_text(encoding<span class="op">=</span><span class="st">"utf-8"</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<section id="оршил" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Оршил</h1>
<p>Сүүлийн жилүүдэд social media хэрэглээ нь мэдээлэл авах, суралцах, харилцах, өөрийгөө илэрхийлэх үндсэн хэрэгслүүдийн нэг болсон. Гэвч хэрэглээний хугацаа хэт уртсах, унтахын өмнөх дэлгэцийн хэрэглээ нэмэгдэх, шөнийн хэрэглээ тогтмолжих зэрэг зан төлөвүүд нь хэрэглэгчийн өдөр тутмын амьдрал, сэтгэлзүйн байдал, анхаарал төвлөрөлд нөлөөлөх боломжтой.</p>
<p>Энэхүү төслийн зорилго нь social media хэрэглээний тоон болон категори өгөгдөл дээр үндэслэн хэрэглэгчийн <code>addiction_level</code> буюу донтолтын түвшинг машин сургалтын статистик арга болох Naive Bayes алгоритмаар ангилах явдал юм.</p>
<p>Судалгааны асуудлыг дараах байдлаар томъёолов.</p>
<blockquote class="blockquote">
<p>Хэрэглэгчийн нас, өдөр тутмын хэрэглээний цаг, платформын тоо, session-ийн дундаж хугацаа, шөнийн хэрэглээ, mental health score, унтахын өмнөх screen time болон хэрэглээний зорилго зэрэг өгөгдлөөр донтолтын түвшинг автоматаар ангилж болох уу?</p>
</blockquote>
<p>Энэхүү асуудал нь тайлбарлагдах боломжтой статистик загвар ашиглан ангилал хийх зорилготой тул төслийн ажлын удирдамжид дурдсан Байесын алгоритмын шаардлагатай нийцэж байна.</p>
</section>
<section id="судалгааны-зорилго-ба-зорилтууд" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Судалгааны зорилго ба зорилтууд</h1>
<section id="ерөнхий-зорилго" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="ерөнхий-зорилго"><span class="header-section-number">2.1</span> Ерөнхий зорилго</h2>
<p>Gen Z хэрэглэгчдийн social media хэрэглээний өгөгдлийг ашиглан донтолтын түвшинг <code>Low</code>, <code>Medium</code>, <code>High</code> гэсэн гурван ангилалд Naive Bayes алгоритмаар ангилах загвар боловсруулах.</p>
</section>
<section id="тусгай-зорилтууд" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="тусгай-зорилтууд"><span class="header-section-number">2.2</span> Тусгай зорилтууд</h2>
<ol type="1">
<li>Өгөгдлийг машин сургалтын загварт ашиглахад тохиромжтой хэлбэрт оруулах.</li>
<li>Тоон болон категори хувьсагчдыг тус тусад нь тохирох магадлалын аргаар боловсруулах.</li>
<li>Naive Bayes загварыг Python хэл дээр гаднын машин сургалтын сан ашиглалгүй хэрэгжүүлэх.</li>
<li>Загварыг сургалтын өгөгдөл дээр сургаж, хөгжүүлэлтийн өгөгдөл дээр шалгах.</li>
<li>Accuracy, precision, recall, F1-score болон confusion matrix ашиглан үр дүнг үнэлэх.</li>
<li>Үр дүнг график дүрслэлээр тайлбарлах.</li>
</ol>
</section>
</section>
<section id="судалгааны-өгөгдөл" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Судалгааны өгөгдөл</h1>
<section id="өгөгдлийн-эх-сурвалж-ба-ерөнхий-тайлбар" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="өгөгдлийн-эх-сурвалж-ба-ерөнхий-тайлбар"><span class="header-section-number">3.1</span> Өгөгдлийн эх сурвалж ба ерөнхий тайлбар</h2>
<p>Судалгаанд <code>genz_social_media_usage_1M.csv</code> нэртэй CSV файл ашигласан. Тус файл нь Gen Z хэрэглэгчдийн social media хэрэглээний шинжүүд болон донтолтын түвшний ангиллыг агуулна.</p>
<p>Эх өгөгдөлд нийт 1,000,000 мөр, дараах үндсэн баганууд орсон.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Нийт мөр:"</span>, metadata[<span class="st">"cleaning_summary"</span>][<span class="st">"rows_before"</span>])</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Target column:"</span>, metadata[<span class="st">"target_column"</span>])</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Тоон хувьсагчид:"</span>, metadata[<span class="st">"numeric_features"</span>])</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Категори хувьсагчид:"</span>, metadata[<span class="st">"categorical_features"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Төслийн ажилд ашигласан хувьсагчдыг дараах байдлаар ангилав.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Төрөл</th>
<th>Хувьсагчид</th>
<th>Тайлбар</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Тоон хувьсагч</td>
<td><code>age</code></td>
<td>Хэрэглэгчийн нас</td>
</tr>
<tr class="even">
<td>Тоон хувьсагч</td>
<td><code>daily_usage_hours</code></td>
<td>Өдөрт social media ашиглах цаг</td>
</tr>
<tr class="odd">
<td>Тоон хувьсагч</td>
<td><code>num_platforms_used</code></td>
<td>Ашигладаг платформын тоо</td>
</tr>
<tr class="even">
<td>Тоон хувьсагч</td>
<td><code>avg_session_minutes</code></td>
<td>Нэг session-ийн дундаж минут</td>
</tr>
<tr class="odd">
<td>Тоон хувьсагч</td>
<td><code>night_usage</code></td>
<td>Шөнийн хэрэглээ байгаа эсэх</td>
</tr>
<tr class="even">
<td>Тоон хувьсагч</td>
<td><code>mental_health_score</code></td>
<td>Сэтгэлзүйн байдлыг илэрхийлэх оноо</td>
</tr>
<tr class="odd">
<td>Тоон хувьсагч</td>
<td><code>screen_time_before_sleep</code></td>
<td>Унтахын өмнөх дэлгэцийн хэрэглээ</td>
</tr>
<tr class="even">
<td>Категори хувьсагч</td>
<td><code>gender</code></td>
<td>Хүйс</td>
</tr>
<tr class="odd">
<td>Категори хувьсагч</td>
<td><code>country</code></td>
<td>Улс</td>
</tr>
<tr class="even">
<td>Категори хувьсагч</td>
<td><code>primary_platform</code></td>
<td>Гол хэрэглэдэг платформ</td>
</tr>
<tr class="odd">
<td>Категори хувьсагч</td>
<td><code>purpose</code></td>
<td>Social media ашиглах гол зорилго</td>
</tr>
<tr class="even">
<td>Target</td>
<td><code>addiction_level</code></td>
<td>Донтолтын түвшин</td>
</tr>
</tbody>
</table>
<p><code>addiction_level</code> багана нь дараах гурван ангилалтай.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(train_data[TARGET_COLUMN].value_counts().sort_index())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="өгөгдөл-бэлтгэл" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="өгөгдөл-бэлтгэл"><span class="header-section-number">3.2</span> Өгөгдөл бэлтгэл</h2>
<p>Өгөгдөл бэлтгэх үед дараах алхмуудыг хийсэн.</p>
<ol type="1">
<li>Шаардлагатай баганууд байгаа эсэхийг шалгасан.</li>
<li>Категори хувьсагчдын хоосон зайг цэвэрлэсэн.</li>
<li>Тоон багануудыг numeric төрөл рүү хөрвүүлсэн.</li>
<li>Missing value байгаа эсэхийг шалгасан.</li>
<li>Тоон багануудад боломжит утгын хязгаарлалт хийсэн.</li>
<li>Давхардсан мөрүүдийг шалгасан.</li>
<li>Өгөгдлийг stratified байдлаар train болон dev хэсэгт хуваасан.</li>
</ol>
<p>Доорх код нь өгөгдөл унших, цэвэрлэх, train/dev split хийх үндсэн функцийг дуудна.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.dataset <span class="im">import</span> read_dataset</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>train_data, dev_data <span class="op">=</span> read_dataset()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Train rows:"</span>, <span class="bu">len</span>(train_data))</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Dev rows:"</span>, <span class="bu">len</span>(dev_data))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Өгөгдөл цэвэрлэгээний хураангуй:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>cleaning <span class="op">=</span> metadata[<span class="st">"cleaning_summary"</span>]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Анхны мөрийн тоо:"</span>, cleaning[<span class="st">"rows_before"</span>])</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Цэвэрлэгээний дараах мөрийн тоо:"</span>, cleaning[<span class="st">"rows_after_cleaning"</span>])</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Давхардал арилгасны дараах мөрийн тоо:"</span>, cleaning[<span class="st">"rows_after_deduplication"</span>])</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Устгасан давхардал:"</span>, cleaning[<span class="st">"duplicates_removed"</span>])</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Missing value:"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(cleaning[<span class="st">"missing_values_before_cleaning"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="train-болон-dev-өгөгдлийн-бүтэц" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="train-болон-dev-өгөгдлийн-бүтэц"><span class="header-section-number">3.3</span> Train болон dev өгөгдлийн бүтэц</h2>
<p>Загварын үнэлгээг бодитой болгохын тулд нийт өгөгдлийн 80 хувийг сургалтад, 20 хувийг хөгжүүлэлтийн шалгалтад ашигласан.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Train class counts"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(train_data[TARGET_COLUMN].value_counts().sort_index())</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Dev class counts"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dev_data[TARGET_COLUMN].value_counts().sort_index())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Ангиллын тархалт:</p>
<p><img src="figures/class_distribution.png" class="img-fluid" data-fig-cap="Сургалтын өгөгдөл дэх донтолтын түвшний тархалт"></p>
<p>Дээрх дүрслэлээс <code>Medium</code> ангилал хамгийн олон, дараа нь <code>Low</code>, харин <code>High</code> ангилал хамгийн бага байгаа нь харагдана. Иймээс зөвхөн accuracy үзүүлэлтээр хязгаарлахгүй, macro F1-score болон ангилал тус бүрийн precision, recall-ийг хамтад нь авч үзэх шаардлагатай.</p>
</section>
<section id="тоон-хувьсагчдын-статистик-шинжилгээ" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="тоон-хувьсагчдын-статистик-шинжилгээ"><span class="header-section-number">3.4</span> Тоон хувьсагчдын статистик шинжилгээ</h2>
<p>Тоон хувьсагчдын ерөнхий статистикийг дараах байдлаар тооцоолов.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>summary_table <span class="op">=</span> train_data[NUMERIC_COLUMNS].describe().T</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(summary_table)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Ангилал тус бүрээр тоон хувьсагчдын дундаж утгыг харьцуулбал:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>feature_means <span class="op">=</span> train_data.groupby(TARGET_COLUMN)[NUMERIC_COLUMNS].mean()</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(feature_means)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="figures/numeric_feature_means.png" class="img-fluid" data-fig-cap="Тоон хувьсагчдын дундаж утгын харьцуулсан дүрслэл"></p>
<p>Энэхүү дүрслэл нь <code>daily_usage_hours</code>, <code>avg_session_minutes</code>, <code>screen_time_before_sleep</code>, <code>mental_health_score</code> зэрэг хувьсагчид ангилал хооронд ялгаатай тархаж байгааг ерөнхийд нь харуулна. Naive Bayes загвар эдгээр ялгааг class conditional distribution буюу ангилал өгөгдсөн нөхцөл дэх тархалтаар ашигладаг.</p>
</section>
</section>
<section id="онолын-үндэс" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Онолын үндэс</h1>
<section id="байесын-теорем" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="байесын-теорем"><span class="header-section-number">4.1</span> Байесын теорем</h2>
<p>Naive Bayes алгоритм нь Байесын теоремд үндэслэдэг. Ангиллын асуудалд тухайн ажиглалт <span class="math inline">\(X\)</span> өгөгдсөн үед <span class="math inline">\(C\)</span> ангилалд хамаарах магадлалыг дараах байдлаар тооцно.</p>
<p><span class="math display">\[
P(C\mid X)=\frac{P(X\mid C)P(C)}{P(X)}
\]</span></p>
<p>Энд:</p>
<ul>
<li><span class="math inline">\(P(C)\)</span> нь тухайн ангиллын урьдчилсан магадлал.</li>
<li><span class="math inline">\(P(X\mid C)\)</span> нь тухайн ангилал өгөгдсөн үед ажиглалт үүсэх нөхцөлт магадлал.</li>
<li><span class="math inline">\(P(C\mid X)\)</span> нь ажиглалт өгөгдсөний дараах ангиллын магадлал.</li>
<li><span class="math inline">\(P(X)\)</span> нь бүх ангилалд ижил тул ангилал сонгох үед тогтмол хэмжигдэхүүн болно.</li>
</ul>
<p>Ангиллын шийдвэрийг хамгийн өндөр posterior probability бүхий ангиллыг сонгох зарчмаар гаргана.</p>
<p><span class="math display">\[
\hat{C}
=
\arg\max_C
P(C\mid X)
\]</span></p>
</section>
<section id="naive-буюу-хараат-бусын-таамаглал" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="naive-буюу-хараат-бусын-таамаглал"><span class="header-section-number">4.2</span> Naive буюу хараат бусын таамаглал</h2>
<p>Naive Bayes загвар нь тайлбарлагч хувьсагчид тухайн ангилал өгөгдсөн нөхцөлд хоорондоо хараат бус гэж үздэг.</p>
<p><span class="math display">\[
P(X_1,X_2,\dots,X_n\mid C)
=
\prod_{i=1}^{n}
P(X_i\mid C)
\]</span></p>
<p>Энэ таамаглал бодит өгөгдөл дээр бүрэн биелэхгүй байж болох ч тооцооллыг хялбаршуулж, олон хувьсагчтай өгөгдөл дээр хурдан, тайлбарлагдах боломжтой ангилал хийх давуу талтай.</p>
<p>Энэхүү судалгаанд <span class="math inline">\(X\)</span> нь хэрэглэгчийн social media хэрэглээний шинжүүдийг илэрхийлнэ.</p>
<p><span class="math display">\[
X =
(x_1,x_2,\dots,x_n)
\]</span></p>
<p>Харин <span class="math inline">\(C\)</span> нь <code>Low</code>, <code>Medium</code>, <code>High</code> донтолтын түвшний аль нэг байна.</p>
</section>
<section id="тоон-хувьсагчдад-gaussian-naive-bayes-ашиглах" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="тоон-хувьсагчдад-gaussian-naive-bayes-ашиглах"><span class="header-section-number">4.3</span> Тоон хувьсагчдад Gaussian Naive Bayes ашиглах</h2>
<p>Тоон хувьсагч бүрийг тухайн ангилал дотор хэвийн тархалттай гэж ойролцоолон үзсэн. Тэгвэл <span class="math inline">\(x_i\)</span> тоон хувьсагчийн нөхцөлт магадлал дараах Gaussian density функцээр илэрхийлэгдэнэ.</p>
<p><span class="math display">\[
P(x_i\mid C)
=
\frac{1}{\sqrt{2\pi\sigma_C^2}}
\exp
\left(
-
\frac{(x_i-\mu_C)^2}{2\sigma_C^2}
\right)
\]</span></p>
<p>Энд:</p>
<ul>
<li><span class="math inline">\(\mu_C\)</span> нь тухайн ангилал дахь хувьсагчийн дундаж.</li>
<li><span class="math inline">\(\sigma_C^2\)</span> нь тухайн ангилал дахь хувьсагчийн дисперс.</li>
</ul>
<p>Загвар сургах үед тоон хувьсагч бүрийн class-wise mean болон variance-ийг тооцсон.</p>
</section>
<section id="категори-хувьсагчдад-laplace-smoothing-ашиглах" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="категори-хувьсагчдад-laplace-smoothing-ашиглах"><span class="header-section-number">4.4</span> Категори хувьсагчдад Laplace smoothing ашиглах</h2>
<p>Категори хувьсагчдын хувьд тухайн утга тухайн ангилалд хэдэн удаа тохиолдсоныг ашиглан нөхцөлт магадлалыг тооцсон.</p>
<p><span class="math display">\[
P(x_i=v\mid C)
=
\frac{
count(v,C)+\alpha
}{
N_C+\alpha(K+1)
}
\]</span></p>
<p>Энд:</p>
<ul>
<li><span class="math inline">\(count(v,C)\)</span> нь <span class="math inline">\(v\)</span> утга <span class="math inline">\(C\)</span> ангилалд тохиолдсон тоо.</li>
<li><span class="math inline">\(N_C\)</span> нь тухайн ангиллын нийт мөрийн тоо.</li>
<li><span class="math inline">\(K\)</span> нь тухайн категори хувьсагчийн боломжит утгын тоо.</li>
<li><span class="math inline">\(\alpha\)</span> нь smoothing параметр.</li>
</ul>
<p>Laplace smoothing ашигласнаар сургалтын өгөгдөлд харагдаагүй шинэ категори утга dev өгөгдөлд таарахад магадлал тэг болохоос сэргийлнэ.</p>
</section>
<section id="log-probability-ашиглах-шалтгаан" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="log-probability-ашиглах-шалтгаан"><span class="header-section-number">4.5</span> Log probability ашиглах шалтгаан</h2>
<p>Олон жижиг магадлалуудыг шууд үржүүлэхэд тоон underflow үүсэх эрсдэлтэй. Иймээс үржвэрийг log probability-ийн нийлбэр болгон хувиргасан.</p>
<p><span class="math display">\[
\log P(C\mid X)
\propto
\log P(C)
+
\sum_{i=1}^{n}
\log P(X_i\mid C)
\]</span></p>
<p>Загварын шийдвэр:</p>
<p><span class="math display">\[
\hat{C}
=
\arg\max_C
\left[
\log P(C)
+
\sum_{i=1}^{n}
\log P(X_i\mid C)
\right]
\]</span></p>
</section>
</section>
<section id="загварын-хэрэгжүүлэлт" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Загварын хэрэгжүүлэлт</h1>
<section id="project-ийн-кодын-бүтэц" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="project-ийн-кодын-бүтэц"><span class="header-section-number">5.1</span> Project-ийн кодын бүтэц</h2>
<p>Төслийн кодыг жишээ repo-ийн загвартай адил <code>src/</code> хавтас дотор модулиар салгасан.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Файл</th>
<th>Үүрэг</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>src/config.py</code></td>
<td>Файлын зам, feature list, target column зэрэг тогтмол тохиргоо</td>
</tr>
<tr class="even">
<td><code>src/dataset.py</code></td>
<td>Өгөгдөл унших, цэвэрлэх, train/dev болгон хуваах</td>
</tr>
<tr class="odd">
<td><code>src/naive_bayes.py</code></td>
<td>Naive Bayes загварын үндсэн хэрэгжүүлэлт</td>
</tr>
<tr class="even">
<td><code>src/metrics.py</code></td>
<td>Accuracy, F1-score, confusion matrix тооцох</td>
</tr>
<tr class="odd">
<td><code>src/visualization.py</code></td>
<td>SVG графикууд үүсгэх</td>
</tr>
<tr class="even">
<td><code>src/main.py</code></td>
<td>Бүх pipeline-г дарааллаар ажиллуулах</td>
</tr>
</tbody>
</table>
</section>
<section id="өгөгдөл-унших-ба-боловсруулах-код" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="өгөгдөл-унших-ба-боловсруулах-код"><span class="header-section-number">5.2</span> Өгөгдөл унших ба боловсруулах код</h2>
<p>Доорх код нь <code>src/dataset.py</code> дотор хэрэгжсэн өгөгдөл унших, бэлтгэх pipeline-г ашиглана.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> src.dataset <span class="im">import</span> read_dataset</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>train_data, dev_data <span class="op">=</span> read_dataset()</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(train_data.head())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Feature болон target-ийг салгав.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>train_features <span class="op">=</span> train_data[FEATURE_COLUMNS]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>train_labels <span class="op">=</span> train_data[TARGET_COLUMN].astype(<span class="bu">str</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>dev_features <span class="op">=</span> dev_data[FEATURE_COLUMNS]</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>dev_labels <span class="op">=</span> dev_data[TARGET_COLUMN].astype(<span class="bu">str</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Feature columns:"</span>, FEATURE_COLUMNS)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Target:"</span>, TARGET_COLUMN)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="naive-bayes-загвар-сургах" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="naive-bayes-загвар-сургах"><span class="header-section-number">5.3</span> Naive Bayes загвар сургах</h2>
<p>Доорх код нь <code>src/naive_bayes.py</code> дотор бичсэн <code>NaiveBayes</code> class-ийг ашиглан загварыг сургана.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> NaiveBayes(alpha<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>model.fit(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    train_features,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    train_labels</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Classes:"</span>, model.classes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Сургалтын дараа загвар дараах үндсэн параметрүүдийг хадгална.</p>
<ol type="1">
<li>Ангилал бүрийн prior probability.</li>
<li>Тоон хувьсагч бүрийн ангилал тус бүр дэх mean болон variance.</li>
<li>Категори хувьсагч бүрийн conditional probability.</li>
<li>Шинэ категори утгад ашиглах smoothed probability.</li>
</ol>
<p>Ангиллын prior probability:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, log_prior <span class="kw">in</span> model.class_log_prior.items():</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(label, <span class="bu">round</span>(log_prior, <span class="dv">4</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Нэг тоон хувьсагчийн class-wise параметрийн жишээ:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label <span class="kw">in</span> model.classes:</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(label, model.numeric_stats[label][<span class="st">"daily_usage_hours"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="таамаглал-гаргах" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="таамаглал-гаргах"><span class="header-section-number">5.4</span> Таамаглал гаргах</h2>
<p>Dev өгөгдөл дээр таамаглал гаргав.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>predictions <span class="op">=</span> model.predict(dev_features)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(predictions[:<span class="dv">20</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="загварын-үнэлгээ" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Загварын үнэлгээ</h1>
<section id="үнэлгээний-хэмжүүрүүд" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="үнэлгээний-хэмжүүрүүд"><span class="header-section-number">6.1</span> Үнэлгээний хэмжүүрүүд</h2>
<p>Ангиллын загварыг дараах хэмжүүрүүдээр үнэлсэн.</p>
<p>Accuracy:</p>
<p><span class="math display">\[
Accuracy =
\frac{
Зөв\ ангилсан\ тоо
}{
Нийт\ ажиглалтын\ тоо
}
\]</span></p>
<p>Precision:</p>
<p><span class="math display">\[
Precision =
\frac{
TP
}{
TP+FP
}
\]</span></p>
<p>Recall:</p>
<p><span class="math display">\[
Recall =
\frac{
TP
}{
TP+FN
}
\]</span></p>
<p>F1-score:</p>
<p><span class="math display">\[
F1 =
\frac{
2 \times Precision \times Recall
}{
Precision + Recall
}
\]</span></p>
<p>Олон ангиллын асуудал тул precision, recall, F1-score-ийг ангилал бүрээр тооцож, macro F1-score-ийг гаргасан.</p>
</section>
<section id="тооцоолсон-үр-дүн" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="тооцоолсон-үр-дүн"><span class="header-section-number">6.2</span> Тооцоолсон үр дүн</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>report <span class="op">=</span> classification_report(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    predictions,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    dev_labels,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    model.classes</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy:"</span>, <span class="bu">round</span>(report[<span class="st">"accuracy"</span>] <span class="op">*</span> <span class="dv">100</span>, <span class="dv">2</span>), <span class="st">"%"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Macro F1:"</span>, <span class="bu">round</span>(report[<span class="st">"macro_f1"</span>] <span class="op">*</span> <span class="dv">100</span>, <span class="dv">2</span>), <span class="st">"%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Ангилал тус бүрийн үзүүлэлт:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>per_class <span class="op">=</span> pd.DataFrame(report[<span class="st">"per_class"</span>]).T</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(per_class)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Үндсэн үр дүнг хүснэгтээр харуулбал:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Үзүүлэлт</th>
<th style="text-align: right;">Утга</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Accuracy</td>
<td style="text-align: right;">93.05%</td>
</tr>
<tr class="even">
<td>Macro F1-score</td>
<td style="text-align: right;">92.29%</td>
</tr>
<tr class="odd">
<td>Dev өгөгдлийн мөр</td>
<td style="text-align: right;">200,000</td>
</tr>
<tr class="even">
<td>Train өгөгдлийн мөр</td>
<td style="text-align: right;">800,000</td>
</tr>
</tbody>
</table>
</section>
<section id="confusion-matrix" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="confusion-matrix"><span class="header-section-number">6.3</span> Confusion matrix</h2>
<p>Confusion matrix нь бодит болон таамагласан ангиллын давхцлыг харуулдаг. Мөр нь бодит ангиллыг, багана нь загварын таамагласан ангиллыг илэрхийлнэ.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> report[<span class="st">"confusion_matrix"</span>][<span class="st">"labels"</span>]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>matrix <span class="op">=</span> pd.DataFrame(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    report[<span class="st">"confusion_matrix"</span>][<span class="st">"matrix"</span>],</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    index<span class="op">=</span>labels,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>labels</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(matrix)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><img src="figures/confusion_matrix.png" class="img-fluid" data-fig-cap="Naive Bayes загварын confusion matrix"></p>
<p>Confusion matrix-ээс дараах ажиглалтуудыг хийж болно.</p>
<ol type="1">
<li><code>Medium</code> ангиллын support хамгийн их тул нийт accuracy-д хүчтэй нөлөөлж байна.</li>
<li><code>Low</code> болон <code>High</code> ангиллууд хоорондоо шууд их андуурагдаагүй байна.</li>
<li><code>High</code> болон <code>Medium</code>, мөн <code>Low</code> болон <code>Medium</code> ангиллын хооронд зарим андуурал гарсан.</li>
<li>Энэ нь дунд түвшний хэрэглээ болон өндөр/бага түвшний зааг зарим хэрэглэгч дээр ойролцоо байж болохыг харуулна.</li>
</ol>
</section>
<section id="ангилал-тус-бүрийн-тайлбар" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="ангилал-тус-бүрийн-тайлбар"><span class="header-section-number">6.4</span> Ангилал тус бүрийн тайлбар</h2>
<p><code>High</code> ангиллын precision 88.99 хувь, recall 91.90 хувь гарсан. Энэ нь загвар өндөр донтолтын түвшинтэй хэрэглэгчдийг ерөнхийдөө сайн илрүүлж байгаа ч зарим <code>Medium</code> хэрэглэгчийг <code>High</code> гэж ангилах тохиолдол байгааг харуулна.</p>
<p><code>Low</code> ангиллын precision 91.63 хувь, recall 93.16 хувь гарсан. Энэ нь бага донтолтын түвшинг таних чадвар өндөр байгааг илэрхийлнэ.</p>
<p><code>Medium</code> ангиллын precision 94.82 хувь, recall 93.31 хувь гарсан. Энэ ангилал хамгийн олон ажиглалттай тул загварын параметр илүү тогтвортой үнэлэгдсэн байх боломжтой.</p>
</section>
</section>
<section id="үр-дүнгийн-хэлэлцүүлэг" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Үр дүнгийн хэлэлцүүлэг</h1>
<p>Загварын accuracy 93.05 хувь гарсан нь нийт dev өгөгдлийн ихэнхийг зөв ангилсныг харуулна. Гэхдээ өгөгдөлд <code>Medium</code> ангилал давамгай байгаа тул accuracy-г дангаар нь тайлбарлах нь хангалтгүй. Иймээс macro F1-score 92.29 хувь гарсан нь ангилал тус бүрийн гүйцэтгэлийг харьцангуй тэнцвэртэй үнэлсэн үзүүлэлт болж байна.</p>
<p>Тоон хувьсагчдын class-wise mean болон variance-ийг ашигласнаар хэрэглээний цаг, session-ийн хугацаа, унтахын өмнөх screen time зэрэг тасралтгүй шинжүүд загварын шийдвэрт оролцсон. Харин <code>gender</code>, <code>country</code>, <code>primary_platform</code>, <code>purpose</code> зэрэг категори шинжүүд хэрэглэгчийн хэрэглээний хэв маягийг нэмэлтээр тайлбарласан.</p>
<p>Энэхүү загварын давуу тал нь:</p>
<ol type="1">
<li>Тооцоолол хурдан.</li>
<li>Бүтэц энгийн.</li>
<li>Магадлалын үндэслэлтэй.</li>
<li>Ангилал тус бүрийн параметрийг тайлбарлах боломжтой.</li>
<li>Том хэмжээний өгөгдөл дээр ажиллахад хөнгөн.</li>
</ol>
<p>Гэхдээ дараах хязгаарлалтууд байна.</p>
<ol type="1">
<li>Naive Bayes нь feature-үүдийг conditional independent гэж үздэг.</li>
<li>Бодит байдал дээр <code>daily_usage_hours</code>, <code>avg_session_minutes</code>, <code>screen_time_before_sleep</code> зэрэг хувьсагчид хоорондоо хамааралтай байх боломжтой.</li>
<li>Тоон хувьсагчид бүрэн Gaussian тархалттай байх албагүй.</li>
<li><code>addiction_level</code> нь өгөгдөлд аль хэдийн өгөгдсөн label тул энэ загвар нь эмнэлзүйн онош биш, зөвхөн өгөгдлийн ангиллын загвар юм.</li>
<li>Өгөгдлийн эх сурвалж, цуглуулах арга, label үүсгэсэн арга тодорхой байх тусам дүгнэлт илүү найдвартай болно.</li>
</ol>
</section>
<section id="ёс-зүйн-анхаарах-зүйл" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Ёс зүйн анхаарах зүйл</h1>
<p>Энэхүү ажлын үр дүнг хэрэглэгчийг оношлох, шошголох, ялгаварлах зорилгоор ашиглах ёсгүй. <code>addiction_level</code> нь судалгааны өгөгдөл дэх ангиллын шошго бөгөөд бодит амьдрал дээр хүний сэтгэлзүйн байдал, хэрэглээний хэв маягийг мэргэжлийн үнэлгээ, нэмэлт мэдээлэлгүйгээр бүрэн тодорхойлох боломжгүй.</p>
<p>Иймээс загварын үр дүнг:</p>
<ol type="1">
<li>Сургалтын зорилгоор,</li>
<li>Өгөгдөл боловсруулах дадлага болгон,</li>
<li>Naive Bayes алгоритмын хэрэглээг ойлгох зорилгоор,</li>
<li>Social media хэрэглээний ерөнхий хэв маягийг судлах туслах хэрэгсэл болгон</li>
</ol>
<p>ашиглах нь зохистой.</p>
</section>
<section id="дүгнэлт" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Дүгнэлт</h1>
<p>Энэхүү төслийн ажлаар Gen Z хэрэглэгчдийн social media хэрэглээний өгөгдөл дээр Naive Bayes ангиллын загвар боловсруулж, донтолтын түвшинг <code>Low</code>, <code>Medium</code>, <code>High</code> гэсэн гурван ангилалд таамаглав.</p>
<p>Судалгааны үр дүнд:</p>
<ol type="1">
<li>1,000,000 мөр өгөгдлийг машин сургалтын загварт тохиромжтой хэлбэрт оруулсан.</li>
<li>Өгөгдлийг 800,000 мөр train, 200,000 мөр dev болгон хуваасан.</li>
<li>Тоон хувьсагчдад Gaussian Naive Bayes, категори хувьсагчдад Laplace smoothing ашигласан.</li>
<li>Загвар 93.05 хувийн accuracy, 92.29 хувийн macro F1-score үзүүлсэн.</li>
<li>Confusion matrix-ээр <code>Medium</code> ангилалд зарим андуурал төвлөрч байгааг тогтоосон.</li>
<li>Naive Bayes алгоритм нь энэхүү өгөгдөл дээр хурдан, ойлгомжтой, статистикийн үндэслэлтэй ангилал хийх боломжтойг харуулсан.</li>
</ol>
<p>Иймээс сонгосон өгөгдөл болон арга зүй нь төслийн ажлын зорилготой нийцэж, машин сургалтын статистик загварыг практикт хэрэглэх шаардлагыг хангаж байна.</p>
</section>
<section id="багийн-гишүүдийн-оролцоо" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Багийн гишүүдийн оролцоо</h1>
<p>Доорх хүснэгтэд багийн гишүүдийн нэр, үүрэг оролцоог бөглөж оруулна.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Багийн гишүүн</th>
<th>Гүйцэтгэсэн ажил</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Нэр 1</td>
<td>Сэдэв сонголт, өгөгдлийн тайлбар, оршил ба дүгнэлт</td>
</tr>
<tr class="even">
<td>Нэр 2</td>
<td>Өгөгдөл бэлтгэл, цэвэрлэгээ, train/dev split</td>
</tr>
<tr class="odd">
<td>Нэр 3</td>
<td>Naive Bayes алгоритмын хэрэгжүүлэлт</td>
</tr>
<tr class="even">
<td>Нэр 4</td>
<td>Үнэлгээний хэмжүүр, confusion matrix, visualization</td>
</tr>
<tr class="odd">
<td>Нэр 5</td>
<td>Quarto тайлан, слайд, эх сурвалж нэгтгэл</td>
</tr>
</tbody>
</table>
</section>
<section id="ашигласан-материал" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Ашигласан материал</h1>
<p>Russell, S., &amp; Norvig, P. (2021). <em>Artificial intelligence: A modern approach</em> (4th ed.). Pearson.</p>
<p>Python Software Foundation. (n.d.). <em>Python documentation</em>. Python.<br>
https://docs.python.org/3/</p>
<p>McKinney, W. (2010). Data structures for statistical computing in Python. <em>Proceedings of the 9th Python in Science Conference</em>, 56-61.</p>
<p>Scikit-learn Developers. (n.d.). <em>Naive Bayes</em>. Scikit-learn.<br>
https://scikit-learn.org/stable/modules/naive_bayes.html</p>
<p>Kaggle. (n.d.). <em>Datasets</em>. Kaggle.<br>
https://www.kaggle.com/datasets</p>
<blockquote class="blockquote">
<p>Тайлбар: Хэрэв <code>genz_social_media_usage_1M.csv</code> өгөгдлийг тодорхой Kaggle dataset эсвэл өөр эх сурвалжаас татсан бол дээрх жагсаалтад тухайн dataset-ийн яг нэр, зохиогч, URL-ийг нэмж оруулна.</p>
</blockquote>
</section>
<section id="хавсралт-ажиллуулах-команд" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Хавсралт: Ажиллуулах команд</h1>
<p>Project-ийн root хавтас дотроос дараах командыг ажиллуулна.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> main.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Virtual environment ашиглах дараалал:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> <span class="at">-m</span> venv .venv</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> .venv/bin/activate</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> <span class="at">-m</span> pip install <span class="at">-r</span> requirements.txt</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> main.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Quarto тайланг PDF болон HTML болгон render хийх:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render report/report.qmd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Хэрэв terminal одоо <code>src/</code> хавтас дотор байгаа бол эхлээд project root руу буцна.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> ..</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render report/report.qmd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>